/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as UserImport } from './routes/_user'
import { Route as StudioImport } from './routes/_studio'
import { Route as IndexImport } from './routes/index'
import { Route as StudioIndexImport } from './routes/_studio/index'
import { Route as UserDashboardImport } from './routes/_user/dashboard'
import { Route as UserMycoursesImport } from './routes/_user/Mycourses'
import { Route as UserBrowsecoursesImport } from './routes/_user/Browsecourses'
import { Route as StudioCreatorStudioImport } from './routes/_studio/creator-studio'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const StudioRoute = StudioImport.update({
  id: '/_studio',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudioIndexRoute = StudioIndexImport.update({
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)

const UserDashboardRoute = UserDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)

const UserMycoursesRoute = UserMycoursesImport.update({
  path: '/Mycourses',
  getParentRoute: () => UserRoute,
} as any)

const UserBrowsecoursesRoute = UserBrowsecoursesImport.update({
  path: '/Browsecourses',
  getParentRoute: () => UserRoute,
} as any)

const StudioCreatorStudioRoute = StudioCreatorStudioImport.update({
  path: '/creator-studio',
  getParentRoute: () => StudioRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_studio': {
      preLoaderRoute: typeof StudioImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_studio/creator-studio': {
      preLoaderRoute: typeof StudioCreatorStudioImport
      parentRoute: typeof StudioImport
    }
    '/_user/Browsecourses': {
      preLoaderRoute: typeof UserBrowsecoursesImport
      parentRoute: typeof UserImport
    }
    '/_user/Mycourses': {
      preLoaderRoute: typeof UserMycoursesImport
      parentRoute: typeof UserImport
    }
    '/_user/dashboard': {
      preLoaderRoute: typeof UserDashboardImport
      parentRoute: typeof UserImport
    }
    '/_studio/': {
      preLoaderRoute: typeof StudioIndexImport
      parentRoute: typeof StudioImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  StudioRoute.addChildren([StudioCreatorStudioRoute, StudioIndexRoute]),
  UserRoute.addChildren([
    UserBrowsecoursesRoute,
    UserMycoursesRoute,
    UserDashboardRoute,
  ]),
  LoginRoute,
  OnboardingRoute,
])

/* prettier-ignore-end */
