/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as StudioIndexImport } from './routes/studio/index'
import { Route as UserDashboardImport } from './routes/user/dashboard'
import { Route as StudioCreatorStudioImport } from './routes/studio/creator-studio'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudioIndexRoute = StudioIndexImport.update({
  path: '/studio/',
  getParentRoute: () => rootRoute,
} as any)

const UserDashboardRoute = UserDashboardImport.update({
  path: '/user/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const StudioCreatorStudioRoute = StudioCreatorStudioImport.update({
  path: '/studio/creator-studio',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/studio/creator-studio': {
      preLoaderRoute: typeof StudioCreatorStudioImport
      parentRoute: typeof rootRoute
    }
    '/user/dashboard': {
      preLoaderRoute: typeof UserDashboardImport
      parentRoute: typeof rootRoute
    }
    '/studio/': {
      preLoaderRoute: typeof StudioIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  OnboardingRoute,
  StudioCreatorStudioRoute,
  UserDashboardRoute,
  StudioIndexRoute,
])

/* prettier-ignore-end */
