/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as LoginImport } from './routes/login'
import { Route as UserImport } from './routes/_user'
import { Route as StudioImport } from './routes/_studio'
import { Route as IndexImport } from './routes/index'
import { Route as UserDashboardImport } from './routes/_user/dashboard'
import { Route as UserMycoursesImport } from './routes/_user/Mycourses'
import { Route as StudioCreatorDashboardImport } from './routes/_studio/creator-dashboard'
import { Route as UserBrowsecourseIndexImport } from './routes/_user/browsecourse_/index'
import { Route as StudioCoursesIndexImport } from './routes/_studio/courses_/index'
import { Route as StudioCoursesVideoIdImport } from './routes/_studio/courses_/$videoId'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const StudioRoute = StudioImport.update({
  id: '/_studio',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserDashboardRoute = UserDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)

const UserMycoursesRoute = UserMycoursesImport.update({
  path: '/Mycourses',
  getParentRoute: () => UserRoute,
} as any)

const StudioCreatorDashboardRoute = StudioCreatorDashboardImport.update({
  path: '/creator-dashboard',
  getParentRoute: () => StudioRoute,
} as any)

const UserBrowsecourseIndexRoute = UserBrowsecourseIndexImport.update({
  path: '/browsecourse/',
  getParentRoute: () => UserRoute,
} as any)

const StudioCoursesIndexRoute = StudioCoursesIndexImport.update({
  path: '/courses/',
  getParentRoute: () => StudioRoute,
} as any)

const StudioCoursesVideoIdRoute = StudioCoursesVideoIdImport.update({
  path: '/courses/$videoId',
  getParentRoute: () => StudioRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_studio': {
      preLoaderRoute: typeof StudioImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_studio/creator-dashboard': {
      preLoaderRoute: typeof StudioCreatorDashboardImport
      parentRoute: typeof StudioImport
    }
    '/_user/Mycourses': {
      preLoaderRoute: typeof UserMycoursesImport
      parentRoute: typeof UserImport
    }
    '/_user/dashboard': {
      preLoaderRoute: typeof UserDashboardImport
      parentRoute: typeof UserImport
    }
    '/_studio/courses/$videoId': {
      preLoaderRoute: typeof StudioCoursesVideoIdImport
      parentRoute: typeof StudioImport
    }
    '/_studio/courses/': {
      preLoaderRoute: typeof StudioCoursesIndexImport
      parentRoute: typeof StudioImport
    }
    '/_user/browsecourse/': {
      preLoaderRoute: typeof UserBrowsecourseIndexImport
      parentRoute: typeof UserImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  StudioRoute.addChildren([
    StudioCreatorDashboardRoute,
    StudioCoursesVideoIdRoute,
    StudioCoursesIndexRoute,
  ]),
  UserRoute.addChildren([
    UserMycoursesRoute,
    UserDashboardRoute,
    UserBrowsecourseIndexRoute,
  ]),
  LoginRoute,
  OnboardingRoute,
])

/* prettier-ignore-end */
